# Generated by Django 3.2.20 on 2023-08-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone Number'),
        ),
    ]
